
pipeline {
    agent any
    
    environment {
        AWS_ACCOUNT_ID = '992382545251'
        AWS_REGION     = 'us-east-1'
        ECR_REPO_NAME  = 'yarin-repo'
        REGISTRY_URL   = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"     
        IMAGE_TAG      = "${env.BRANCH_NAME.replaceAll('/', '-')}-build-${env.BUILD_NUMBER}"        
        PROD_IP        = "54.165.111.130" 
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Image') {
            steps {
                dir('calculator_app') {
                    script {
                        sh "docker build -t ${REGISTRY_URL}/${ECR_REPO_NAME}:${IMAGE_TAG} ."
                    }
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    echo "Running tests in 'tests' directory..."   
                    sh "docker run --rm ${REGISTRY_URL}/${ECR_REPO_NAME}:${IMAGE_TAG} python -m unittest discover -v -s tests -p 'test_*.py'"
                }
            }
        }

        stage('Push & Deploy (CD)') {
            when { branch 'main' } // רק כשממזגים ל-main
            steps {
                script {
                    sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${REGISTRY_URL}"
                    sh "docker push ${REGISTRY_URL}/${ECR_REPO_NAME}:${IMAGE_TAG}"
                    sshagent(['ec2-ssh-key']) {
                        sh """
                            ssh -o StrictHostKeyChecking=no ec2-user@${PROD_IP} '
                                aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${REGISTRY_URL}
                                docker pull ${REGISTRY_URL}/${ECR_REPO_NAME}:${IMAGE_TAG}
                                docker stop my-calculator-app || true
                                docker rm my-calculator-app || true
                                docker run -d --name my-calculator-app -p 80:5000 ${REGISTRY_URL}/${ECR_REPO_NAME}:${IMAGE_TAG}
                            '
                        """
                    }
                }
            }
        }

        stage('Health Verification') {
            when { branch 'main' }
            steps {
                script {
                    echo "Waiting for app to start..."
                    sleep 10
                    sh "curl -f http://${PROD_IP}/health || curl -f http://${PROD_IP}/"
                }
            }
        }
    }

    post {
        always {
            sh "docker rmi ${REGISTRY_URL}/${ECR_REPO_NAME}:${IMAGE_TAG} || true"
        }
    }
}
