pipeline {
    agent any
    
    environment {
        AWS_ACCOUNT_ID = '992382545251'
        AWS_REGION     = 'us-east-1'
        ECR_REPO_NAME  = 'yarin-repo'
        IMAGE_TAG      = "${env.GIT_COMMIT.take(7)}"
        REGISTRY_URL   = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Login to ECR') {
            steps {
                script {
                    sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${REGISTRY_URL}"
                }
            }
        }

        stage('Build Image') {
            steps {
                dir('calculator_app') {
                    script {  
                        sh "docker build -t ${REGISTRY_URL}/${ECR_REPO_NAME}:${IMAGE_TAG} ."
                    }
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('calculator_app') {
                    script {                    
                        sh "docker run --rm ${REGISTRY_URL}/${ECR_REPO_NAME}:${IMAGE_TAG} python -m unittest discover"
                    }
                }
            }
        }

        stage('Push to ECR') {
            steps {
                script {
                    sh "docker push ${REGISTRY_URL}/${ECR_REPO_NAME}:${IMAGE_TAG}"
                }
            }
        }
    }

    post {
        always {      
            sh "docker rmi ${REGISTRY_URL}/${ECR_REPO_NAME}:${IMAGE_TAG} || true"
        }
    }
}
